server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .html
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8