server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  resources:
    chain:
      cache: false # static content caching disable

  security:
    oauth2:
      client:
        client-id: foo
        client-secret: bar

